/**
 * Fallback content — used when Sanity is empty (before first content push)
 * or when running locally without env vars.
 * This is the v3.1 hardcoded content as a single source of truth.
 */

export const fallbackContent = {
  es: {
    site: {
      brand: 'Viva Yoga',
      brandItalic: 'con Connie',
      tagline: 'Vinyasa & beach yoga en la Costa del Sol',
      nav: {
        about: 'Sobre',
        classes: 'Clases',
        schedule: 'Horario',
        pricing: 'Precios',
        gallery: 'Galería',
        contact: 'Contacto',
      },
    },
    hero: {
      eyebrow: 'Bienvenida',
      headline: 'Vive tu práctica,',
      headlineItalic: 'respira el mar.',
      subheadline:
        'Vinyasa flow y yoga de playa al amanecer en la Costa del Sol. Conecta cuerpo, respiración y Mediterráneo.',
      ctaText: 'Reserva tu primera clase',
      ctaLink: '#contacto',
    },
    about: {
      eyebrow: 'Sobre Connie',
      headline: 'El yoga como vuelta',
      headlineItalic: 'a lo esencial.',
      body: 'Connie te invita a descubrir el yoga en su forma más auténtica — fluir con la respiración, conectar con el cuerpo y dejarse llevar por el ritmo del mar.',
      stats: [
        { value: '+5', label: 'años enseñando' },
        { value: 'ES · EN', label: 'clases bilingües' },
        { value: 'Todos', label: 'los niveles' },
      ],
    },
    classes: [
      {
        id: 'vinyasa',
        eyebrow: 'Estudio',
        title: 'Vinyasa',
        titleItalic: 'Flow.',
        body: 'Secuencias dinámicas vinculadas con la respiración. Un espacio para construir fuerza, flexibilidad y presencia. Todos los niveles bienvenidos — desde principiante hasta práctica avanzada de invertidas.',
        details: ['60 minutos', 'Jueves 9:30 AM', 'Evolve Studio, Estepona'],
        ctaText: 'Reservar',
        image: 'connie-vinyasa.png',
      },
      {
        id: 'beach',
        eyebrow: 'Playa',
        title: 'Beach',
        titleItalic: 'Yoga.',
        body: 'Vinyasa suave al amanecer frente al Mediterráneo. La arena bajo los pies, la luz dorada, el sonido del mar. Una experiencia que recordarás.',
        details: ['75 minutos', 'Horarios según temporada y mareas', 'Costa de Estepona'],
        ctaText: 'Reservar',
        image: 'connie-beach.png',
      },
    ],
    schedule: {
      eyebrow: 'Horario semanal',
      headline: 'Reserva tu momento.',
      rows: [
        { day: 'Lunes', time: '—', class: 'consultar WhatsApp' },
        { day: 'Martes', time: '—', class: 'consultar WhatsApp' },
        { day: 'Miércoles', time: '—', class: 'consultar WhatsApp' },
        { day: 'Jueves', time: '09:30 — 10:30', class: 'Vinyasa Flow · Evolve Studio, Estepona', highlight: true },
        { day: 'Viernes', time: '—', class: 'consultar WhatsApp' },
        { day: 'Sábado', time: '—', class: 'consultar WhatsApp' },
        { day: 'Domingo', time: 'descanso', class: '—' },
      ],
      footer: 'Las sesiones de playa se confirman cada mañana por WhatsApp según mareas y meteorología. Clases privadas disponibles bajo petición.',
    },
    pricing: {
      eyebrow: 'Precios',
      headline: 'Pago por práctica,',
      headlineItalic: 'sin ataduras.',
      tiers: [
        {
          name: 'Clase suelta',
          price: '15€',
          subtitle: 'para probar',
          features: ['1 clase (60-75 min)', 'Esterilla proporcionada', 'Sin compromiso'],
          ctaText: 'Reservar',
          popular: false,
        },
        {
          name: 'Bono 10 clases',
          price: '120€',
          subtitle: '12€ por clase',
          features: ['10 clases', 'Válido 3 meses', 'Estudio o playa', 'Esterilla incluida'],
          ctaText: 'Comprar bono',
          popular: true,
          popularLabel: 'Más popular',
        },
        {
          name: 'Mensual',
          price: '90€',
          subtitle: 'ilimitado',
          features: ['Clases ilimitadas', 'Válido 30 días', 'Estudio + playa', 'Prioridad reservas'],
          ctaText: 'Suscribirme',
          popular: false,
        },
      ],
      footer: 'Pago en efectivo, Bizum o transferencia. Primera clase siempre a 10€.',
    },
    gallery: {
      eyebrow: 'Galería',
      headline: 'Momentos',
      headlineItalic: 'de práctica.',
      images: [
        { src: 'connie-gal-1.png', alt: 'Handstand' },
        { src: 'connie-gal-2.png', alt: 'Hands in prayer' },
        { src: 'connie-gal-3.png', alt: 'Meditation' },
        { src: 'connie-gal-4.png', alt: 'Warrior I' },
        { src: 'connie-gal-5.png', alt: 'Tree pose' },
        { src: 'connie-gal-6.png', alt: 'Top-down mat' },
        { src: 'connie-gal-7.png', alt: 'Side plank' },
        { src: 'connie-gal-8.png', alt: "Child's pose" },
      ],
    },
    contact: {
      eyebrow: 'Contacto',
      headline: 'Reserva o pregúntame',
      headlineItalic: 'lo que quieras.',
      subheadline: 'Te respondo en menos de 24h. Si es para hoy, mejor WhatsApp.',
      whatsapp: { label: 'WhatsApp', value: '+34 XXX XXX XXX', href: 'https://wa.me/34XXXXXXXXX' },
      email: { label: 'Email', value: 'hola@vivayogaconnie.com', href: 'mailto:hola@vivayogaconnie.com' },
      instagram: { label: 'Instagram', value: '@vivayogaconnie', href: 'https://www.instagram.com/vivayogaconnie/' },
      whereLabel: 'Dónde',
      where: [
        { title: 'Evolve Studio', subtitle: 'Estepona, Costa del Sol' },
        { title: 'Playa', subtitle: 'Costa de Estepona, Marbella' },
      ],
    },
    footer: {
      tagline: 'Vinyasa & beach yoga en la Costa del Sol',
      copyright: '© 2026 Viva Yoga con Connie',
    },
  },
  en: {
    site: {
      brand: 'Viva Yoga',
      brandItalic: 'with Connie',
      tagline: 'Vinyasa & beach yoga on the Costa del Sol',
      nav: {
        about: 'About',
        classes: 'Classes',
        schedule: 'Schedule',
        pricing: 'Pricing',
        gallery: 'Gallery',
        contact: 'Contact',
      },
    },
    hero: {
      eyebrow: 'Welcome',
      headline: 'Live your practice,',
      headlineItalic: 'breathe the sea.',
      subheadline: 'Vinyasa flow and sunrise beach yoga on the Costa del Sol. Connect body, breath, and the Mediterranean.',
      ctaText: 'Book your first class',
      ctaLink: '#contact',
    },
    about: {
      eyebrow: 'About Connie',
      headline: 'Yoga as a return',
      headlineItalic: 'to what matters.',
      body: 'Connie invites you to discover yoga in its most authentic form — flow with your breath, connect with your body, and let the rhythm of the sea carry you.',
      stats: [
        { value: '+5', label: 'years teaching' },
        { value: 'ES · EN', label: 'bilingual classes' },
        { value: 'All', label: 'levels welcome' },
      ],
    },
    classes: [
      {
        id: 'vinyasa',
        eyebrow: 'Studio',
        title: 'Vinyasa',
        titleItalic: 'Flow.',
        body: 'Dynamic breath-linked sequences. A space to build strength, flexibility, and presence. All levels welcome — from beginner to advanced inversions practice.',
        details: ['60 minutes', 'Thursday 9:30 AM', 'Evolve Studio, Estepona'],
        ctaText: 'Book',
        image: 'connie-vinyasa.png',
      },
      {
        id: 'beach',
        eyebrow: 'Beach',
        title: 'Beach',
        titleItalic: 'Yoga.',
        body: 'Soft sunrise Vinyasa facing the Mediterranean. Sand under your feet, golden light, the sound of the sea. An experience to remember.',
        details: ['75 minutes', 'Times vary by season and tides', 'Estepona coastline'],
        ctaText: 'Book',
        image: 'connie-beach.png',
      },
    ],
    schedule: {
      eyebrow: 'Weekly schedule',
      headline: 'Find your moment.',
      rows: [
        { day: 'Monday', time: '—', class: 'ask on WhatsApp' },
        { day: 'Tuesday', time: '—', class: 'ask on WhatsApp' },
        { day: 'Wednesday', time: '—', class: 'ask on WhatsApp' },
        { day: 'Thursday', time: '09:30 — 10:30', class: 'Vinyasa Flow · Evolve Studio, Estepona', highlight: true },
        { day: 'Friday', time: '—', class: 'ask on WhatsApp' },
        { day: 'Saturday', time: '—', class: 'ask on WhatsApp' },
        { day: 'Sunday', time: 'rest', class: '—' },
      ],
      footer: 'Beach sessions are confirmed each morning via WhatsApp based on tides and weather. Private classes available on request.',
    },
    pricing: {
      eyebrow: 'Pricing',
      headline: 'Pay per practice.',
      headlineItalic: 'No lock-in.',
      tiers: [
        {
          name: 'Drop-in',
          price: '€15',
          subtitle: 'to try it out',
          features: ['1 class (60-75 min)', 'Mat provided', 'No commitment'],
          ctaText: 'Book',
          popular: false,
        },
        {
          name: '10-class pack',
          price: '€120',
          subtitle: '€12 per class',
          features: ['10 classes', 'Valid 3 months', 'Studio or beach', 'Mat included'],
          ctaText: 'Buy pack',
          popular: true,
          popularLabel: 'Most popular',
        },
        {
          name: 'Monthly',
          price: '€90',
          subtitle: 'unlimited',
          features: ['Unlimited classes', 'Valid 30 days', 'Studio + beach', 'Priority booking'],
          ctaText: 'Subscribe',
          popular: false,
        },
      ],
      footer: 'Pay in cash, Bizum, or bank transfer. First class always €10.',
    },
    gallery: {
      eyebrow: 'Gallery',
      headline: 'Moments',
      headlineItalic: 'of practice.',
      images: [
        { src: 'connie-gal-1.png', alt: 'Handstand' },
        { src: 'connie-gal-2.png', alt: 'Hands in prayer' },
        { src: 'connie-gal-3.png', alt: 'Meditation' },
        { src: 'connie-gal-4.png', alt: 'Warrior I' },
        { src: 'connie-gal-5.png', alt: 'Tree pose' },
        { src: 'connie-gal-6.png', alt: 'Top-down mat' },
        { src: 'connie-gal-7.png', alt: 'Side plank' },
        { src: 'connie-gal-8.png', alt: "Child's pose" },
      ],
    },
    contact: {
      eyebrow: 'Contact',
      headline: 'Book a class or',
      headlineItalic: 'ask anything.',
      subheadline: 'I reply within 24h. If it\'s for today, WhatsApp is fastest.',
      whatsapp: { label: 'WhatsApp', value: '+34 XXX XXX XXX', href: 'https://wa.me/34XXXXXXXXX' },
      email: { label: 'Email', value: 'hola@vivayogaconnie.com', href: 'mailto:hola@vivayogaconnie.com' },
      instagram: { label: 'Instagram', value: '@vivayogaconnie', href: 'https://www.instagram.com/vivayogaconnie/' },
      whereLabel: 'Where',
      where: [
        { title: 'Evolve Studio', subtitle: 'Estepona, Costa del Sol' },
        { title: 'Beach', subtitle: 'Estepona coastline, Costa del Sol' },
      ],
    },
    footer: {
      tagline: 'Vinyasa & beach yoga on the Costa del Sol',
      copyright: '© 2026 Viva Yoga with Connie',
    },
  },
};

export type Locale = 'es' | 'en';
export type Content = typeof fallbackContent.es;
